### ISSUE TITLE
Seeing "JSONCollections is not defined"

### ISSUE THREAD

**Issue by boaticus** [ephemer/meteor-json-collections#1]
I added the package to my meteor install, created a file in my /server dir with the name "mmj.mmjParticipants.collection.json"

When I try to read from the collection, I see:

(from a file I have called /lib/collections.js)
Participants = JSONCollections.mmjParticipants;
if (Participants.find().count() === 0) {
  console.log("No participants.");
};

I'm getting "JSONCollections is not defined"

Any ideas what I may have done to get this?

**Comment by ephemer** [comment]
Hi, are you getting this error on the client or the server? At what point do you see it?

I think the problem may be with Meteor's load order rules (everything in the 'lib' directory will be loaded before other code). Try putting your code in a `Meteor.startup()` block:

```
Meteor.startup(function(){
 // your code
});
```

**Comment by boaticus** [comment]
I was referencing it in a file in my /lib folder. I'll try wrapping it in a startup method as you suggested.

**Comment by boaticus** [comment]
Yep, still same error, even when wrapped in a Meteor.startup.

![image](https://cloud.githubusercontent.com/assets/1961242/7568015/0aea8a36-f7c6-11e4-8b9e-ff6433d22269.png)

![image](https://cloud.githubusercontent.com/assets/1961242/7568023/1400f11e-f7c6-11e4-9d38-13ec05616690.png)

The test json file lives at /private/tester.collection.json

**Comment by ephemer** [comment]
Hi Ken,

the file has to be named like this, otherwise it won’t be recognised and JSONCollections won’t exist:

something.collection_name.collection.json

**Comment by boaticus** [comment]
That was it. Thanks!

**Comment by ephemer** [comment]
My pleasure, glad you got it working!
